ALTER TABLE file_info
    ADD COLUMN created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE file_info SET created_time = CURRENT_TIMESTAMP, updated_time = CURRENT_TIMESTAMP;